# .github/workflows/deploy-mkdocs.yml
name: Deploy mkdocs on new tag

# Trigger on sem-version tag
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

# gh-pages needs a push, so grant write; read is implied
permissions:
  contents: write

concurrency: docs        # auto-cancel superseded runs

jobs:
  deploy:
    if: github.repository == 'singular-genomics/g4x-helpers' # Avoid running in forks that copy this workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version-file: "pyproject.toml"
          enable-cache: false

      - name: Sync dependencies from uv.lock
        run: uv sync --frozen --only-dev

      - name: Deploy to GitHub Pages
        env:
          TAG: ${{ github.ref_name }}      # e.g. v1.2.3
        run: |
          uv run mkdocs gh-deploy --force --clean --message "docs: $TAG"
